const { withAppBuildGradle } = require('@expo/config-plugins');

// `android/` is gitignored and regenerated by `expo prebuild`, so we can't just
// edit the Gradle files by hand. This config plugin injects a `release` signing
// config (driven by -PKDC_UPLOAD_* properties passed in CI) every time the
// native project is generated, and points the release build type at it.
//
// When the properties are absent (e.g. a plain local `assembleRelease`), the
// release config simply has no keystore — debug builds are unaffected.

const RELEASE_SIGNING_CONFIG = `
        release {
            if (project.hasProperty('KDC_UPLOAD_STORE_FILE')) {
                storeFile file(project.property('KDC_UPLOAD_STORE_FILE'))
                storePassword project.property('KDC_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('KDC_UPLOAD_KEY_ALIAS')
                keyPassword project.property('KDC_UPLOAD_KEY_PASSWORD')
            }
        }`;

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    // 1) Add the `release` signing config (idempotent).
    if (!contents.includes("project.hasProperty('KDC_UPLOAD_STORE_FILE')")) {
      contents = contents.replace(/signingConfigs\s*\{/, (m) => `${m}${RELEASE_SIGNING_CONFIG}`);
    }

    // 2) Point the release build type at the release signing config.
    const before = contents;
    contents = contents.replace(
      /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?signingConfig\s+signingConfigs\.)debug/,
      '$1release',
    );
    if (contents === before && !contents.includes('signingConfig signingConfigs.release')) {
      throw new Error(
        'withReleaseSigning: could not point the release build type at signingConfigs.release. ' +
          'The Expo Android template changed — update plugins/withReleaseSigning.js.',
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
};
